name: Limit Duplications

on: [push, pull_request]

jobs:
  limit-duplications:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install jscpd
      run: sudo npm install -g jscpd

    - name: No Duplication beyond 3 lines and 35 tokens
      run: jscpd ./ --min-lines 3 --min-tokens 35 --threshold 0 --mode strict
